version: '3.8'

services:
  user-service:
    image: user-service
    ports:
      - "9090:9090"
    networks:
      - my_network

  welcome-service:
    image: welcome-service
    ports:
      - "9091:9091"
    networks:
      - my_network

networks:
  my_network: